package by.epam.trjava.tutorsystem.controller.command;

public enum CommandName {
    AUTHORIZATION,
    GOTOLOGINPAGE,
    GOTOREGISTRATIONPAGE,
    REGISTRATION,
    ADDNEWTEST,
    GOTOADDNEWTEST,
    SHOWALLTESTS,
    GOTOSHOWALLTESTSPAGECOMMAND,
    TESTINFO,
    GOTOSHOWTESTINFOPAGECOMMAND,
    LOGOUT,
    COMMANDMISSING,
    DELETETEST,
    EDITTEST,

    VIEWPERSONALCABINET,
    EDITUSER,
    GOTOPERSONALCABINET,

    ADDNEWSUBJECT,
    ADDNEWQUESTION,
    ADDNEWANSWER,
    GOTOADDNEWSUBJECT,
    GOTOADDNEWQUESTION,
    GOTOADDNEWANSWER



}
