package by.epam.trjava.tutorsystem.controller.command;

public enum CommandName {
    AUTHORIZATION,
    GOTOLOGINPAGE,
    GOTOREGISTRATIONPAGE,
    REGISTRATION,
    ADDNEWTEST,
    GOTOADDNEWTEST,
    SHOWALLTESTS,
    GOTOSHOWALLTESTSPAGECOMMAND,
    TESTINFO,
    GOTOSHOWTESTINFOPAGECOMMAND,
    LOGOUTCOMMAND,
    COMMANDMISSING,
    DELETETEST,
    EDITTEST
}
